MelodySequencer.class SongBook.class Melody.class Note.class: MelodySequencer.java SongBook.java Melody.java Note.java
	javac MelodySequencer.java
	javac SongBook.java
	javac Melody.java
	javac Note.java
#	
clean: 
	rm *.class
